### ISSUE TITLE
국회/광역/기초/광역단체장/기초단체장 스크랩할 웹사이트 조사

### ISSUE THREAD

**Issue by Re-st** [NewWays-TechForImpactKAIST/main#21]
- 국회/광역/기초/광역단체장/기초단체장 (뉴웨이즈 대표님 의견) 도 기초의원에서 하는 것처럼 가능한 웹사이트나, 혹은 정당 페이지가 있을까요?
- 국회의원, 기초단체장은 수가 적어 정당 페이지 하나에 모여 있을 수 있습니다.
  - 그러나, 정당 페이지는 국가기관 페이지에 비해 불안정
  - 당장 당명을 바꾸면 도메인, 구조부터 바뀔 듯
- 따라서 국가기관 페이지를 조사해 주시길 부탁드립니다!

**Comment by Re-st** [comment]
관련 이슈 
https://github.com/NewWays-TechForImpactKAIST/main/issues/5#issuecomment-1741692195

**Comment by Re-st** [comment]
진행상황 (희원)
- [광역의회 페이지 조사 완료](https://docs.google.com/spreadsheets/d/1fBDJjkw8FSN5wXrvos9Q2wDsyItkUtNFGOxUZYE-h0M/edit#gid=1775254616) 
  - 서울시를 예로 들면, `<input class="memLinkk" onClick="goMember('1117')" title="더불어민주당성북구 제3선거구" data-url='1117' value='강동길'/>`  식이라 당 조사가 쉬울 듯함
- [광역,기초단체장 모인 페이지](https://www.laiis.go.kr/lips/mlo/lcl/groupHeadList.do#) (정당정보는 바로 나오지 않음)

**Comment by Re-st** [comment]
진행상황 (기연)
기초의회 웹사이트 링크 고쳐서 [새로 만듦](https://docs.google.com/spreadsheets/d/1fBDJjkw8FSN5wXrvos9Q2wDsyItkUtNFGOxUZYE-h0M/edit#gid=1127955905)
- 깨진 링크 수정
  - 접속 안되는 사이트 조사
- 의원 소속정당이 표시되어 있지 않은 사이트 조사
  - 특정 링크를 타고 들어가야 표시되어 있는 경우, 해당 경로 조사

**Comment by withSang** [comment]
국회의 경우, 열린국회정보 정보공개포털에서 제명/사퇴 여부를 알 수 있어 활용이 가능해보입니다!
- [열린국회정보 제21대 국회의원검색](https://open.assembly.go.kr/portal/assm/search/memberSchPage.do)에서 임기가 끝나지 않은 현역 의원 명단 조회가 가능합니다. 자진 사퇴한 의원(윤희숙 전 의원, 박완수 전 의원 등)은 명단에서 제외됩니다.
	- 이름 / 정당 / 소속위원회 / 지역구 / 성별 / 당선횟수 / 당선방법으로 구성
		- 당선횟수: 초선/재선/3선 등
		- 당선방법: 지역구/비례대표 중 하나
- [열린국회정보 역대 국회의원 통합현황](https://open.assembly.go.kr/portal/assm/search/memberHistSchPage.do)에서는 사퇴/제명한 의원을 포함한 역대 국회의원(제헌~21대) 명단 조회가 가능합니다.
	- 이름 / 정당 / 소속위원회 / 지역구 / 성별 / 당선횟수 / 당선방법으로 구성
		- 당선횟수: 초선/재선/3선 등
		- 당선방법: 지역구/비례대표 중 하나
