### ISSUE TITLE
어떤 부분의 통계가 필요할지 뉴웨이즈 대표님과 논의 

### ISSUE THREAD

**Issue by Re-st** [NewWays-TechForImpactKAIST/main#5]

**Comment by Re-st** [comment]
1. 분야 : 성별, 나이, 정당, 등등
2. 공식 : 어떻게 측정할 것인가 (비율? 경향? 가중치는?)..

**Comment by Re-st** [comment]
iii. 선출단위 : 기초의원? 광역의원 포함? 다양한 계층의 데이터가 필요할 수 있다. 한편, 뉴웨이즈의 포커스는 기초의원일 수도 있다.

**Comment by keonly** [comment]
오전 중에 대표님께 개별 연락을 드렸는데요, 대표님께서 현재 코로나로 인해 몸상태가 좋지 않으시다고 하셔서 답변이 늦어질 것 같습니다. 답변 전달받는 대로 다시 공유드리겠습니다.

**Comment by keonly** [comment]
대표님께서 답변 주신 내용 전달드립니다~
1. 통계를 계산할 대상이 되는 항목은 이전처럼 성별, 연령대, 정당 이렇게 셋으로 충분할까요? (크롤링을 통해 얻을 수 있는 정보 역시 이 정도인 것으로 파악됩니다.)
>네, 성별/연령대/정당 충분할 거 같습니다. 더 욕심내면 더 할 수 있지만 데이터 수집이 균질하지 않을 거 같아요.
2. 이전에 전달해 주신 자료에서는 [Gini-Simpson Diversity Index](https://en.wikipedia.org/wiki/Diversity_index#Gini%E2%80%93Simpson_index)를 이용한 것으로 알고 있습니다. 혹시 해당 통계량을 이용하도록 결정한 이유가 어떻게 되는지 알 수 있을까요?(생태계 다양성을 계산하기 위해 고안된 척도인 것으로 알고 있는데, 이 지표가 사회학 분야에서도 널리 사용되는지 궁금합니다.) 또, 이번 프로젝트에서도 동일한 통계량을 이용하여도 좋을지, 아니면 다른 추천하시거나 시도해 보고 싶으신 통계량이 있으신지 알려주시면 감사하겠습니다!
>결정 배경은 이전에 보내드렸던 [구글 독스 링크](https://docs.google.com/document/d/1zDRcU9ytQJv-7DPrxgRqOsd4_tevCYVfspJO1eKLzfc/edit)에서 확인해봐주시면 좋을 거 같습니다. 사회학 분야에서 널리 사용된다기 보다 당시 기간 내 연구 분석에서 가장 적절한 방법을 찾았습니다. 그 질적 접근의 한계는 첫 비대면 미팅 때 설명드린 바와 같습니다.
3. 이전에 전달해 주신 자료는 기초의원만을 대상으로 다양성이 평가되었는데요, 이 범위 역시 이번 프로젝트에서 동일하게 가져가게 될까요? 구체적으로는 저희 팀에서 광역의원이나 국회의원의 데이터를 포함하여 보다 다양한 계층의 데이터를 제공하여야 할지 논의 중이었는데요, 뉴웨이즈의 포커스가 기초의원이라면 이 부분은 크게 필요하지 않을 것 같아서 이렇게 여쭙습니다.
>뉴웨이즈는 모든 선출단위를 중요하게 여깁니다! 국회/광역/기초/광역단체장/기초단체장까지 확대되어서 분석되면 더 유의미할 거라 기대됩니다.
